apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-flask
    spec:
      containers:
      - name: hello-world-flask
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000
          protocol: TCP

